<a href="https://colab.research.google.com/github/PauliusPadrostis/BootCampWork/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

---
# Create a vector of numbers from 1 to 9

In [5]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

---
# Create a vector of 10 zeros

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---
# Create a vector of 10 ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

---
# Create a vector of 10 fours

In [10]:
np.ones(10) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

---
# Create a vector of even numbers from 0 to 100

In [12]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

---
# Create a matrix of 25 members starting at 1 and ending at 25. Assign it to a variable.

In [22]:
nums = np.arange(1, 26)
nums = nums.reshape(5,5)
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

---
# Pull the number 12 from the matrix

In [25]:
nums[2, 1]

12

---
# Extract the last row from the matrix.

In [28]:
nums[4, 0:5]

array([21, 22, 23, 24, 25])

---
# Extract the submatrix from the matrix

1, 2, 3

6, 7, 8

11,12,13

In [30]:
nums[0:3, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

---
# Extract the submatrix from the matrix

7,  8,  9,  10

12, 13, 14, 15

17, 18, 19, 20


In [36]:
nums[1:4, 1:5]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

---
# Extract the submatrix from the matrix

16, 17, 18

21, 22, 23

In [43]:
nums[3:5, 0:3]

array([[16, 17, 18],
       [21, 22, 23]])

---
# Create a vector of 20 random values ​​from 0 to 1. Assign to a variable.

In [49]:
randy = np.random.rand(20)
randy

array([0.28894259, 0.72503062, 0.08361018, 0.21749693, 0.25009481,
       0.1990198 , 0.62720402, 0.78098892, 0.74479885, 0.22771751,
       0.00873366, 0.03290063, 0.52909192, 0.3411941 , 0.27657641,
       0.5292404 , 0.33567648, 0.97190651, 0.10955311, 0.19448513])

---
# Find the largest value in an array and its index.

In [50]:
randy.max(), randy.argmax()

(0.9719065144957296, 17)

---
# Find the smallest value and its index

In [51]:
randy.min(), randy.argmin()

(0.008733661502632994, 10)

---
# Print the data type of this array

In [56]:
type(randy[1]), type(randy)

(numpy.float64, numpy.ndarray)

---
# Create a vector of integer values ​​from 1 to 100. Assign to a variable. Subtract all numbers greater than 90 from it

In [73]:
numss = np.arange(1, 101)
numss_bools = numss > 90
numss[numss_bools]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

---
# Subtract all multiples of 7 from the vector

In [80]:
nums_mult = [num % 7 == 0 for num in numss]
numss[nums_mult]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

---
# Create the following matrix:

array(
  
        [[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],

        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],

        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],

        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],

        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


In [85]:
x = np.arange(0.025, 1.025, 0.025)
x.reshape(5, 8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

---
# Create the following matrix (whole numbers from 2 to 1000 from which you can get a whole root):

array(
        
        [[  4,   9,  16,  25,  36],

        [ 49,  64,  81, 100, 121],

        [144, 169, 196, 225, 256],

        [289, 324, 361, 400, 441],

        [484, 529, 576, 625, 676],

        [729, 784, 841, 900, 961]])

In [109]:
y = np.arange(2, 1001)

In [110]:
y_root = np.array([num for num in y if np.sqrt(num).is_integer()])
y_reshaped = y_root.reshape(-1, 5)

y_reshaped

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])